# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: Hello DevOps

email: yihungjen@gmail.com

description: > # document head meta and feed.xml site description
    A DevOps, Engineer, Half-and-half Social Retard foraging into the wild
    wonderlands of post Cloud Computing rukus and miscellaneous things
    happening to me in life.

exclude: [README.md]

baseurl: "/hello-devops" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site

image_url: "http://s3-ap-northeast-1.amazonaws.com/hello-devops" # provider hostname for image

# permalink pattern for generated posts
# NOTE: categories will be added from Frontmatter categories variable
#
permalink: "/blog/:categories/:year/:month/:day/:title/"

twitter_username: yihungjen

github_username: jeffjen

# Build settings
markdown: kramdown

# Use Github Flavored Markdown
kramdown:
  input: GFM

# Enable gist tag
gems:
  - jekyll-gist
